name: Run Autodoist

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  run-autodoist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Autodoist
      env:
        TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Optional
      run: |
        python main.py
